name: central_do_musico_pro
description: "Central do Músico Pro - Aplicativo de alta performance."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Base original e funcionalidades de navegação
  cupertino_icons: ^1.0.6
  receive_sharing_intent: ^1.0.0
  # Motor de processamento e Parser web
  just_audio: ^0.9.36
  http: ^1.1.0
  html: ^0.15.4
  # Afinador e permissões de hardware
  permission_handler: ^11.0.1
  pitch_detector_dart: 0.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/cifras/
    - assets/data/