name: Executar Compilacao Final

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Baixar o codigo nativo do projeto
      uses: actions/checkout@v4

    - name: 2. Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 3. Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: 4. Instalar as dependencias
      run: flutter pub get

    - name: 5. Rodar a compilacao
      run: flutter build apk --release