name: Testar Build Padrao do Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o codigo nativo do projeto
      uses: actions/checkout@v4

    - name: 2. Configurar Java Padrao do Mercado
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 3. Configurar Flutter Atualizado
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # Ele vai usar a versão estável mais recente do Flutter automaticamente

    - name: 4. Instalar as dependencias padrao do seu pubspec
      run: flutter pub get

    - name: 5. Rodar a compilacao automatica do projeto
      run: flutter build apk --release
